### PR TITLE
Big bang review

### PR DESCRIPTION
**Pull request by ErichDonGubler**
Individual commits are items of review. Since this...isn't a normal review flow, let's do this to keep things sane:

* Examine individual commits and comment on THOSE. Top-level discussion will probably just muddy which commit belongs to what, and the reason that that's interesting here is because it's REALLY easy to filter commits out before a merge.
* I was hoping for at least some response for most of the comment-only commits. :)  They're not worth checking in by themselves!
* Holler if you don't understand or want to know why I'm so gosh-darned opinionated on hunks that don't have `WIP` or `review` in the commit message.

### CODE REVIEW

**Review by yan-zaretskiy — COMMENTED** [review]
Could have cases with 10's of thousands of elements in those vectors.

**Comment by yan-zaretskiy** [comment]
>  /// erichdongubler: The size here is necessary because this potentially hasn't been constructed
    /// yet, right? I wonder if it'd be worth having a "canonical" struct similar to this that
    /// guarantees fully constructed data at the type level. It's hard to want to do that for a
    /// single variant, but if you wanted to publish this as a lib I'd encourage you to consider
    /// it.
    ///
    /// Another way that this could be done is by using this as the canonical representation
    /// everywhere except in construction paths like `parsing::keyword_header`, and use a tuple to
    /// indicate the number of elements expected. That would actually normalize well with how
    /// you're doing it already!

Entirely lost here! The reason I need to keep the size value around is so that I know how many bytes to grab from the binary file for that particular data type. String is the only type where the size need to be explicit.

**Comment by yan-zaretskiy** [comment]
```
/// erichdongubler: How often are the number of elements here small? I'm wondering if using
/// something like [`smallvec`](https://docs.rs/smallvec) might be an interesting optimization
/// option here.
```
Is `smallvec` a nightly-only crate? This makes me uncomfortable. Or are there features from it that can be used on stable? To answer the first question, metadata is short but the bulk of parsing is spent on the data itself, and the number of elements there depends on what the simulator chose to output. Could go into thousands.

**Comment by yan-zaretskiy** [comment]
```
// erichdongubler: This looks like this should consume `self` and return it again if we don't
// error out here. Why? Well..there's no guarantee that this method actually recovers the read
// stream correctly and that one can call `Self::next_keyword` again and expect sane results!
// Or even worse, what if we fail the first time for valid reasons, attempt to read again, and
// the (decidedly garbage) stream you're getting just HAPPENS to have things that look like
// valid ECL data?
//
// This would make it impossible to continue with an `Iterator` implementation for
// `EclBinFile`, but...it's not a bad API to have a special flavor of iteration if correctness
// calls for it!
```
This sounds really good!

**Comment by yan-zaretskiy** [comment]
```
/// erichdongubler: I'm honestly not a fan of this `Iterator` implementation. Why not just make
/// client code do this?
```
Could you elaborate? Is this due to the improved ability to handle incorrect inputs described in the previous point? I want to make sure I understand when implementing the `Iterator` trait might not be a good idea.

**Comment by yan-zaretskiy** [comment]
```
/// erichdongubler: would it be worth having a separate struct with fields always expected to
/// be here?
```
Time data is the only one that is always present. Would wrapping it with a new type yield any benefits?

**Comment by yan-zaretskiy** [comment]
```
/// erichdongubler: I'm a bit confused about the error story now. Looks like you're using this enum
/// in some but not all places, and they're immediately getting converted into `anyhow::Error`s?
/// Perhaps this is an artifact of being a WIP.
///
/// Before you go publishing a crate, it'd be best to have one or maybe more families of error
/// enumerations for your library operations. In the meantime, using `anyhow` in the lib is fine, I
/// just want to make sure I understand and that the ideal I have is understood. :)
```
Need your insight on errors explained in more detail... I think what you are saying is that I should put `anyhow` at the `fn main()` level, but return actual error types from the library functions, right? I will work on this.

**Comment by yan-zaretskiy** [comment]
```
/// erichdongubler: You would probably better served using the `log` crate
/// and the right filter instead of having a `debug` flag here. It would
/// let clients control if things output AND how it's logged.
```
Sounds reasonable, need to look into the crate.

**Comment by ErichDonGubler** [comment]
Did everything get absorbed from here? Should I close this?

**Comment by yan-zaretskiy** [comment]
Yeah, you can close it! The only remaining item is the error management overhaul, which is on my TODO list.

**Pull request closed without merging**
